version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: lion-roar-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://localhost:4000

networks:
  default:
    driver: bridge